# Generated by Django 5.2.7 on 2025-12-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_alter_tiktokauthor_username_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadhistory',
            options={'ordering': ['-download_date']},
        ),
        migrations.AlterField(
            model_name='tiktokauthor',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='original_url',
            field=models.URLField(db_index=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
