# Generated by Django 5.2.7 on 2025-12-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_alter_downloadhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokauthor',
            name='username',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='cover_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='original_url',
            field=models.URLField(db_index=True, max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='tiktokvideo',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
